### ISSUE TITLE
Indentation bug with plugin 10.0.0

### ISSUE THREAD

**Issue by kenyee** [JLLeitschuh/ktlint-gradle#472]
For this kind of indentation:
```
class BrandInteractor @Inject constructor(
    something: Something
) : MyInteractor<BrandContract.View,
    BrandContract.Presenter,
    BrandContract.Interactor,
    BrandContract.Tracker,
    BrandContract.Router
>(
    repository,
    tracker
),
    BrandContract.Interactor {
```

The 10.0.0 plugin does this incorrectly as:
```
class BrandInteractor @Inject constructor(
    something: Something
) : MyInteractor<BrandContract.View,
        BrandContract.Presenter,
        BrandContract.Interactor,
        BrandContract.Tracker,
        BrandContract.Router
    >(
        repository,
        tracker
    ),
    BrandContract.Interactor {
```

which doesn't match the IntelliJ ktlint plugin.
I also tried setting the ktlint version to 0.41.0 and 0.40.0 and 0.39.0 via ktlint {version = "xxx" } w/o luck.  I verified it looks at this by setting it to zzzzzz it can't find zzzzz.

Rolling back the plugin to 9.4.1 seems to work find and I can still use version= to force ktlint to 0.41.0 which is the latest.

**Comment by Tapchicoma** [comment]
Could you provide full file with dependencies or some repro project?

**Comment by fondesa** [comment]
We have the same exact problem. Unfortunately, we can't reproduce it on some repro-project.
I'll leave here some information which could be helpful to fix that:
- it happens only when ktlint 0.41.0 is used through this Gradle plugin. When the binary of ktlint 0.41.0 is invoked manually on the same sources, it works correctly.
- we are using Kotlin 1.5.0
- we are using a `indent_size` and a `continuation_indent_size` of 2
- changing the indentation to the one suggested by this plugin doesn't fix the problem, because, after that, the plugin suggests to return to the previous indentation. I'll make an example here to be clearer:

```bash
/path/Dummy.kt:261:7 Unexpected indentation (expected 4, actual 6)
```

After changing it to `4`, we get:
```bash
/path/Dummy.kt:261:7 Unexpected indentation (expected 6, actual 4)
```
