### ISSUE TITLE
Android sample eveventually not applying custom settings

### ISSUE THREAD

**Issue by mobilekosmos** [JLLeitschuh/ktlint-gradle#647]
In my project's build.gradle I set the plugin like this:

```
buildscript {
...
}
plugins {
    id 'org.jlleitschuh.gradle.ktlint' version '11.2.0'
}
```

If I put the configuration block below

```
ktlint {
            version = "0.48.2"
            ignoreFailures = true
            outputToConsole = false
            verbose = false
        }
```

This configuration is ignored. Only if I put it here it works:

```
afterEvaluate {
    subprojects {
        apply plugin: 'com.android.library'
        apply plugin: "org.jlleitschuh.gradle.ktlint"
        ktlint {
            version = "0.48.2"
            ignoreFailures = true
            outputToConsole = false
            verbose = false
        }
    }
}
```

Is this expected?

**Comment by wakingrufus** [comment]
ktlint-gradle applies only to the project you apply the plugin to. if you apply it to the parent project, then it will not touch the subprojects. This is proper behavior of a gradle plugin, so yes it is expected.

I recommend putting
 ```
plugins {
    id 'org.jlleitschuh.gradle.ktlint' version '11.2.0' apply(false)
``` 
in your parent build.gradle and 
```
plugins {
    id 'org.jlleitschuh.gradle.ktlint' version '11.2.0'
}
``` 
in each subproject, instead of using afterEvaluate and the subprojects closure
